const editProfileContext = {
  pageTitle: 'Редактирование профиля',
  name: 'Иван Иванов',
  inputs: [
    {
      settings: true,
      name: 'Почта',
      key: 'email',
      componentName: 'inputEmail',
      type: 'text',
      value: 'test@yandex.ru',
      readonly: false,
    },
    {
      settings: true,
      name: 'Логин',
      key: 'login',
      componentName: 'inputLogin',
      type: 'text',
      value: 'SomeLogin123',
      readonly: false,
    },
    {
      settings: true,
      name: 'Имя',
      key: 'name',
      componentName: 'inputName',
      type: 'text',
      value: 'Иван',
      readonly: false,
    },
    {
      settings: true,
      name: 'Фамилия',
      key: 'lastname',
      componentName: 'inputLastname',
      type: 'text',
      value: 'Иванов',
      readonly: false,
    },
    {
      settings: true,
      name: 'Имя в чате',
      key: 'chat-name',
      componentName: 'inputChatName',
      type: 'text',
      value: 'Иван',
      readonly: false,
    },
    {
      settings: true,
      name: 'Телефон',
      key: 'phone',
      componentName: 'inputPhone',
      type: 'text',
      value: '+7 (999) 999 99 99',
      readonly: false,
    },
  ],
  buttons: [
    {
      text: 'Сохранить',
      buttonClass: 'common',
      componentName: 'buttonSave',
    },
  ],
};
export default editProfileContext;
